name: testing
services:
  api:
    image: poi9912/agriculture-api:latest
    depends_on:
      microcks:
        condition: service_started
    environment:
      - HOST=localhost
      - ENV=sb
      - ENDPOINT=http://microcks:8080/rest/agriculture-api/1.0.0
      - TIMEOUT=5000
    restart: unless-stopped
    ports:
      - 3000:3000
  importer:
    image: poi9912/agriculture-mock-importer:latest
    depends_on:
      api:
        condition: service_started
  microcks:
    image: quay.io/microcks/microcks-uber:latest-native
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - microcksdata:/deployments/config
volumes:
  microcksdata:
