services:
  api:
    image: poi9912/agriculture-api:latest
    environment:
      - host=localhost
        env=sb
    ports:
      - 3000:3000
    restart: unless-stopped
  importer:
    image: poi9912/agriculture-mock-importer:latest
    depends_on:
      microcks:
        condition: service_started
  microcks:
    image: quay.io/microcks/microcks-uber:latest-native
    ports:
      - 8085:8080
  
