global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
      monitor: 'agriculture-api'
rule_files:
  - "alert.rules"
scrape_configs:
  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets: ['reverse-proxy:8899']
         