name: deploy

on: workflow_call
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: download artifacts
              uses: houqp/download-release-assets-action@v1.0.1
              with: 
                repo: Poi9912/agriculture
                match: "agriculture.zip"
                rename: agriculture.zip
            - name: copy to server
              uses: kostya-ten/ssh-server-deploy@v4
              with:
                host: ${{ secrets.DEPLOY_HOST }}
                port: ${{ secrets.DEPLOY_PORT }}
                username: ${{ secrets.DEPLOY_USER }}
                private_key: ${{ secrets.DEPLOY_SSH_KEY }}
                scp_source: agriculture.zip
                scp_target: ${{ secrets.DEPLOY_WORKDIR }}
                before_script: |
                  pwd && ls -la
                after_script: |
                  pwd && ls -la
                
            # - name: SSH commands
            #   uses: nekiro/ssh-job@main
            #   with: 
            #     host: ${{ secrets.DEPLOY_HOST }}
            #     user: ${{ secrets.DEPLOY_USER }}
            #     key: ${{ secrets.DEPLOY_SSH_KEY }}
            #     port: ${{ secrets.DEPLOY_PORT }}
            #     command: |
            #         cd ${{ secrets.DEPLOY_WORKDIR }}
            #         unzip agriculture.zip
            #         rm agriculture.zip 
            #         docker compose up -d --remove-orphans --pull always
            #         exit