name: build

on:
  push:
    branches: ['main']
    paths: ['api/**','mocks/**','unit-testing/**','.github/workflows/onchanges.yml','.github/workflows/test.yml']
  pull_request:
    branches: ['main']
    paths: ['api/**','mocks/**','unit-testing/**','.github/workflows/onchanges.yml','.github/workflows/test.yml']
    
jobs:
  call-test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  call-publish:
    needs: [call-test]
    uses: ./.github/workflows/publishbuild.yml
    secrets: inherit
  call-deploy:
    needs: [call-publish]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
  