name: build pull request

on:
  pull_request:
    branches: ['main']
    paths: ['api/**','mocks/**','unit-testing/**']
    
jobs:
  call-test:
    uses: ./.github/workflows/test.yml
    secrets: inherit