name: release

on:
    push:
        tags:
            - v*

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4.1.7
            - name: removes containerized components from release
              run: |
                rm -r $(ls -DAI monitoring | grep -v compose)
            - name: zips release artifact
              run: |
                zip -r agriculture.zip *
            - name: Create GitHub release
              id: create-new-release
              uses: ncipollo/release-action@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                artifacts: agriculture.zip
                artifactContentType: application/zip
                prerelease: false
    call-deploy:
        needs: [release]
        uses: ./.github/workflows/deploy.yml
        secrets: inherit