name: release

on:
    push:
        tags:
            - v1.*

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4.1.7
            - name: removes containerized components from release
              run: |
                rm -rf agriculture-api
                rm -rf mocks 
                rm -rf .git*
#                - rm -rf unit-testing
            - name: zips release artifact
              run: |
                zip -r agriculture.zip *
            - run: |
                ls -la
            - name: Create GitHub release
              id: create-new-release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{  github.ref_name }}
                release_name: Release ${{  github.ref_name }}
                prerelease: false
            - name: Upload release asset
              uses: actions/upload-release-asset@v1
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create-new-release.outputs.upload_url }}
                asset_path: ./agriculture.zip
                asset_name: agriculture-${{  github.ref_name }}.zip
                asset_content_type: application/zip
