name: version

on: workflow_call

jobs:
    tag_release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: checkout
              uses: actions/checkout@v4.1.7
            - name: Get Previous tag
              id: previoustag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"
              with:
                fallback: v1.0.0 # Optional fallback tag to use when no tag can be found
            - run: echo $"${{steps.previoustag.outputs.tag}}"
            - name: 'Get next minor version'
              id: nextversion
              uses: "WyriHaximus/github-action-next-semvers@v1"
              with:
                version: ${{ steps.previoustag.outputs.tag }}
            - run: echo $"${{steps.nextversion.outputs.v_patch}}"
            - name: 'Create new gh release'
              id: createmilestone
              uses: "WyriHaximus/github-action-create-milestone@v1"
              with:
                title: ${{ steps.nextversion.outputs.v_patch }}
              env:
                GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            - name: removes containerized components from release
              run: |
                rm -r $(ls -DAI monitoring | grep -v compose)
            - name: zips release artifact
              run: |
                zip -r agriculture.zip *
            - name: Create GitHub release
              id: create-new-release
              uses: ncipollo/release-action@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                artifacts: agriculture.zip
                artifactContentType: application/zip
                prerelease: false
    